<?php
/** @var $block \Magento\Catalog\Block\Product\View */
$product = $block->getProduct();

$price = $product->getFinalPrice() ?: $product->getPrice() ;
$isActiveFinancialInfo = $block->getFinancialActive();
$cuit = $block->getCuit();// or tax_id
//stablish the initial url with only one product selected
$url_information = "https://mobbex.com/p/sources/widget/arg/" . $cuit . "/?total=" . $price;
?>

<?php if ($product->isSaleable() && $isActiveFinancialInfo && $cuit > 0) : ?>
    <div class="mobbex-finance" data-price="<?= $price ?>" data-cuit="<?= $cuit ?>">

        <!-- If the tax_id and active="Si" is set !-->
        <div class="box-tocart">
            <div class="fieldset">
                <div class="actions">
                    <!-- The Button !-->
                    <button class="action primary tocart" id="btn_mobbex_installments"><?= __('View Installments') ?></button>
                    <?= $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>

        <!-- The Modal -->
        <div id="modal_mobbex" class="modal ">
            <!-- Modal content -->
            <div class="modal-content">
                <span  class="button_mobbex_close close">&times;</span>
                <iframe id="mobbex_iframe" src=<?php echo $url_information ?>></iframe>
            </div>
        </div>
    </div>

<?php endif; ?>
