<?php if ($block->getProduct()->isSaleable() && $block->getFinancialActive() && $block->getCuit() > 0) : ?>
    <div class="mbbx-widget">
        <button class="action primary" id="mbbx-open-widget"><?= __('View Installments') ?></button>
        <div id="modal-mobbex">
            <div id="mbbx-modal-content">
                <span id="mbbx-close-widget">&times;</span>
                <iframe id="mbbx-iframe" src="<?= "https://mobbex.com/p/sources/widget/arg/{$block->getCuit()}/?total={$block->getProduct()->getFinalPrice()}" ?>"></iframe>
            </div>
        </div>
    </div>

    <style>
        #modal-mobbex {
            position: fixed;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: hidden;
            background-color: rgba(0, 0, 0, 0.4);
            z-index: 9999;
            display: none;
            place-items: center;
        }

        #mbbx-modal-content {
            background: rgb(236, 242, 246);
            border-radius: 10px;
            z-index: 10000;
            width: 100%;
            height: 90%;
            max-width: 600px;
            padding: 0;
            display: flex;
            flex-flow: column;
            align-items: end;
        }

        #mbbx-iframe {
            width: 100%;
            height: 100%;
            border: none;
            border-radius: 16px;
        }

        #mbbx-close-widget {
            color: #4e4e4e;
            font-size: 28px;
            background: white;
            width: 38px;
            text-align: center;
            border-radius: 100%;
            margin: 10px;
            height: 38px;
            text-decoration: none;
        }

        #mbbx-close-widget:hover,
        #mbbx-close-widget:focus {
            color: black;
            cursor: pointer;
        }

        .scroll-lock {
            padding-right: 17px;
            overflow: hidden;
        }
    </style>
    <script>
        require(['jquery', 'domReady!'], function ($) {
            let cont  = document.querySelector('.mbbx-widget')
            let modal = document.getElementById("modal-mobbex");
            let open  = document.getElementById('mbbx-open-widget');
            let close = document.getElementById('mbbx-close-widget');

            cont.addEventListener('click', function(event) {
                event.preventDefault();

                if (event.target == modal || event.target == close) {
                    modal.style.display = "none";
                } else if (event.target == open) {
                    modal.style.display = "grid";
                } else {
                    return;
                }

                document.body.classList.toggle('scroll-lock');

                return false;
            });
        });
    </script>
<?php endif;