<div class="pos-list">
    <h2 class="checkbox-title">Selecciona tus POS</h2>
    <div class="checkbox-list">
        <?php foreach ($this->posList as $pos): ?>
            <div class="checkbox-item">
                <div class="pos-input">
                    <input 
                        type="checkbox" 
                        id="<?= $pos['reference'] ?>" 
                        name="mobbex_pos[]" value="<?= $pos['value'] ?>" 
                        <?= in_array($pos['value'], $this->selectedPos) ? 'checked' : '' ?>
                    >
                    <label for="<?= $pos['reference'] ?>"><?= $pos['label'] ?></label>
                </div>
                <p class="checkbox-description"> <?= $pos['description'] ?></p>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<style>
    .pos-list {
        border: 1px solid #ccc;
        padding: 20px;
        border-radius: 10px;
        background-color: #f9f9f9;
        margin: 0 auto;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        max-width: 65%;
    }

    .checkbox-title {
        font-size: 1.5rem;
        margin-bottom: 15px;
        color: #333;
        text-align: center;
    }

    .checkbox-list {
        display: flex;
        flex-direction: column;
        gap: 20px;
    }

    .checkbox-item {
        display: flex;
        flex-direction: column;
        gap: 5px;
        padding: 10px;
        border-radius: 5px;
        transition: background-color 0.3s;
    }

    .checkbox-item input[type="checkbox"] {
        margin-right: 10px;
        cursor: pointer;
    }

    .pos-input {
        display: flex;
    }

    .checkbox-item label {
        font-size: 1.2rem;
        color: #333;
        font-weight: bold;
        cursor: pointer;
    }

    .checkbox-description {
        font-size: 0.9rem;
        color: #666;
        margin-left: 25px;
    }

    .checkbox-item:hover {
        background-color: #f0f0f0;
    }

    .checkbox-item:hover label {
        color: #007BFF;
    }

    .checkbox-item input[type="checkbox"]:checked+label {
        color: #007BFF;
        text-decoration: underline;
    }
</style>