<?php $checkout = $this->getCheckoutUrl(); ?>

<form id="redirect_form" action="<?php echo $checkout['url']; ?>" method="GET">
    <p><?php echo __("We are redirecting you to our secure payment site in Mobbex..."); ?>
    <input type='hidden' name='paymentMethod' value='<?php echo $checkout['method']; ?>'/>
</form>

<script type="text/javascript">
    document.getElementById("redirect_form").submit();
</script>
