<h3><?= $this->escapeHtml(__('Payment plans')) ?></h3>
<p><?= $this->escapeHtml(__('The enabled plans will appeared in the checkout for this product')) ?></p>
<input type="hidden" name="mbbx_options_loaded" value="1" data-form-part="<?= $this->escapeHtml($this->form) ?>">

<?php
$id   = isset($this->params['id']) ? $this->params['id'] : 0;

foreach ($this->config->catalogSettings as $value) {
    if ($this->type == 'category' && strpos('subscription', $value) !== false)
        continue;

    ${$value} = $this->config->getCatalogSetting($id, $value, $this->type);
}

try {
    extract(\Mobbex\Repository::getPlansFilterFields($id, $common_plans, $advanced_plans));
} catch (\Exception $e) {
    $commonFields = $advancedFields = $sourceNames = $sourceGroups = [];
    $this->logger->log('error', "Template > getContent | {$e->getMessage()}");
}

/** TEMPLATE PLANS FILTER  */
?>

<table class="mbbx-plans-cont">
    <tbody>
        <tr style="text-align: center;">
            <td><?= $this->escapeHtml(__('Common Plans')) ?></td>
            <td><?= $this->escapeHtml(__('Advanced Plans')) ?></td>
        </tr>
        <tr>
            <td class="mbbx-plans">
                <?php foreach ($commonFields as $field) : ?>
                    <div class="mbbx-plan">

                        <div class="source-popover">
                            <h4>Medios Disponibles</h4>
                            <?php foreach ($sourceGroups[$field['label']] as $sourceRef) : ?>
                                <div class="mbbx-plan-group">
                                    <img src="https://res.mobbex.com/images/sources/original/<?= $this->escapeHtml($sourceRef); ?>.png">
                                    <small><?= isset($sourceNames[$sourceRef]) ? $this->escapeHtml($sourceNames[$sourceRef]) : $this->escapeHtml($sourceRef) ?></small>
                                </div>
                            <?php endforeach; ?>
                        </div>

                        <div class="mbbx-plan-cont">
                            <input type="checkbox" name="<?= $this->escapeHtml($field['id']) ?>" <?= $field['value'] ? 'checked="checked"' : '' ?> id="<?= $this->escapeHtml($field['id']) ?>" data-form-part="<?= $this->escapeHtml($this->form) ?>">
                            <label for="<?= $this->escapeHtml($field['id']) ?>"><?= $this->escapeHtml($field['label']) ?></label>
                        </div>

                        <p class="description"><?= $this->escapeHtml($field['description']) ?></p>

                    </div>
                <?php endforeach; ?>
            </td>

            <td class="mbbx-plans">
                <?php foreach ($advancedFields as $sourceRef => $fields) : ?>
                    <div class="mbbx-plan-source">
                        <img src="https://res.mobbex.com/images/sources/png/<?= $this->escapeHtml($sourceRef) ?>.png">
                        <p><?= $this->escapeHtml($sourceNames[$sourceRef]) ?></p>
                    </div>
                    <?php foreach ($fields as $field) : ?>
                        <div class="mbbx-plan-advanced">
                            <input type="checkbox" name="<?= $this->escapeHtml($field['id']) ?>" <?= $field['value'] ? 'checked="checked"' : '' ?> id="<?= $this->escapeHtml($field['id']) ?>" data-form-part="<?= $this->escapeHtml($this->form) ?>">
                            <label for="<?= $this->escapeHtml($field['id']) ?>"><?= $this->escapeHtml($field['label']) ?></label>
                            <p class="description"><?= $this->escapeHtml($field['description']) ?></p>
                        </div>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </td>
        </tr>
    </tbody>
</table>

<?php

/** TEMPLATE MULTIVENDOR */

?>
<div style="margin-top: 20px;">
    <h3><?= $this->escapeHtml(__('Split y Multivendor')) ?></h3>
    <p><?= $this->escapeHtml(__('Asocie otra entidad de Mobbex a este producto/categoría')) ?></p>
    <label for="entity"><?= $this->escapeHtml(__('UID de la entidad')) ?></label>
    <input id="entity" name="entity" type="text" value="<?= $this->escapeHtml($entity) ?>" data-form-part="<?= $this->escapeHtml($this->form) ?>">
</div>

<?php

/** TEMPLATE SUBSCRIPTION MODE */

if ($this->type == 'product') {
?>
    <div class="mbbx-subscription">
        <h3><?= $this->escapeHtml(__('Suscripciones')) ?></h3>
        <p><?= $this->escapeHtml(__('Asocie una suscripción existente a este producto')) ?></p>
        <div id="subscription_uid" style="margin-top: 20px;">
            <label style="margin-right: 10px;" for="sub_uid"><?= $this->escapeHtml(__('UID de la suscripción')) ?></label>
            <input type="text" name="sub_uid" id="sub_uid" value="<?= $this->escapeHtml($subscription_uid) ?>" data-form-part="<?= $this->escapeHtml($this->form) ?>">
        </div>
    </div>
<?php
}

$this->eventManager->dispatch('mobbex' . ucfirst($this->type) . 'Settings', false, $id);


/** STYLES */

?>
<style>

    .mbbx-plan {
        position: relative;
    }


    .mbbx-plans-cont {
        border: 1px gainsboro solid;
        width: 500px;
    }

    .mbbx-plans-cont tbody {
        vertical-align: top
    }

    .mbbx-plans-cont td {
        width: 50%;
        border: 1px gainsboro solid;
        padding: 15px;
    }

    .mbbx-plans-cont label {
        font-weight: 400 !important;
    }

    .mbbx-plans-cont .description {
        color: grey;
        font-size: 1.2rem;
    }

    .mbbx-plan-advanced {
        padding-left: 20px;
    }

    .mbbx-plan-source * {
        display: inline;
    }

    .mbbx-plan-source img {
        width: 30px;
        border-radius: 100%;
    }

    .mbbx-plan-cont {
        display: flex;
        align-items: center;
        padding: 0 10px;
    }

    .mbbx-plan-group {
        display: flex;
        justify-content: left;
        align-items: center;
        padding: 5px;
        background-color: #eaeffb;
    }

    .mbbx-plan-group img {
        width: 1.5em;
        margin: 0 5px;
    }

    .source-popover {
        display: none;
        position: absolute;
        left: 12em;
        max-width: 15em;
        width: 100%;
        border-radius: 5px;
        background-color: #eaeffb;
        padding: 1rem;
        z-index: 100;
    }

    .source-popover h3 {
        text-align: center;
    }

    .mbbx-plan:hover .source-popover {
        display: block;
    }

    .mbbx-plan-group p {
        margin: 0;
    }

    .hidden {
        display: none;
    }

    .mbbx-subscription {
        margin-top: 20px;
    }
</style>