<h3><?= $this->escapeHtml(__('Payment plans')) ?></h3>
<p><?= $this->escapeHtml(__('The enabled plans will appeared in the checkout for this product')) ?></p>
<input type="hidden" name="mbbx_options_loaded" value="1" data-form-part="<?= $this->escapeHtml($this->form) ?>">

<?php
$id   = isset($this->params['id']) ? $this->params['id'] : 0;

foreach ($this->config->catalogSettings as $value) {
    if ($this->type == 'category' && strpos('subscription', $value) !== false)
        continue;

    ${$value} = $this->config->getCatalogSetting($id, $value, $this->type);
}

try {
    $filtered_plans = json_encode(\Mobbex\Repository::getPlansFilterFields($id));
} catch (\Exception $e) {
    $commonFields = $advancedFields = $sourceNames = $sourceGroups = [];
    $this->logger->log('error', "Template > getContent | {$e->getMessage()}");
}

/** TEMPLATE PLANS FILTER  */
?>
<div id="mbbx-plans-configurator" style="display:flex"></div>
<?php

/** TEMPLATE MULTIVENDOR */
?>
<div style="margin-top: 20px;">
    <h3><?= $this->escapeHtml(__('Split y Multivendor')) ?></h3>
    <p><?= $this->escapeHtml(__('Asocie otra entidad de Mobbex a este producto/categoría')) ?></p>
    <label for="entity"><?= $this->escapeHtml(__('UID de la entidad')) ?></label>
    <input id="entity" name="entity" type="text" value="<?= $this->escapeHtml($entity) ?>" data-form-part="<?= $this->escapeHtml($this->form) ?>">
</div>

<?php

/** TEMPLATE SUBSCRIPTION MODE */
if ($this->type == 'product') {
?>
    <div class="mbbx-subscription">
        <h3><?= $this->escapeHtml(__('Suscripciones')) ?></h3>
        <p><?= $this->escapeHtml(__('Asocie una suscripción existente a este producto')) ?></p>
        <div id="subscription_uid" style="margin-top: 20px;">
            <label style="margin-right: 10px;" for="sub_uid"><?= $this->escapeHtml(__('UID de la suscripción')) ?></label>
            <input type="text" name="sub_uid" id="sub_uid" value="<?= $this->escapeHtml($subscription_uid) ?>" data-form-part="<?= $this->escapeHtml($this->form) ?>">
        </div>
    </div>
<?php
}

$this->helper->executeHook('mobbex' . ucfirst($this->type) . 'Settings', false, $id);


/** STYLES */

?>
<style>
    .hidden {
        display: none;
    }

    .mbbx-subscription {
        margin-top: 20px;
    }
</style>
<script id="mbbx-finance-data">
    window.platformFormName        = "<?=$this->escapeHtml($this->form)?>";
    window.mobbexSources           = <?= isset($filtered_plans) ? $filtered_plans : "[]" ?>;
    window.mobbexSelectedPlans     = <?= isset($selected_plans) ? json_encode($selected_plans) : "[]" ?>;
    window.mobbexFeaturedPlans     = <?= isset($featured_plans) ? json_encode($featured_plans) : "[]" ?>;
    window.mobbexAdvancedPlans     = <?= isset($advanced_plans) ? json_encode($advanced_plans) : "[]" ?>;
    window.mobbexManual            = Boolean(<?= isset($manual_config) ? $manual_config == "yes" : 0 ?>);
    window.mobbexShowFeaturedPlans = Boolean(<?= isset($show_featured) ? $show_featured == "yes" : 0 ?>);
</script>
<script src="<?= $block->getViewFileUrl('Mobbex_Webpay::js/plans-configurator.min.js') ?>"></script>