<h3><?= __('Plans Configuration') ?></h3>
<p><?= __('The enabled plans will appeared in the checkout for all the products in this category') ?></p>
<input type="hidden" name="mbbx_options_loaded" value="1" data-form-part='category_form'>

<?php
$id     = isset($this->params['id']) ? $this->params['id'] : 0;
$form   = 'category_form';

foreach ($this->config->catalogSettings as $value) {
    if (!strpos('subscription', $value))
        ${$value} = $this->config->getCatalogSetting($id, $value, 'category');
}

try {
    // extract(\Mobbex\Repository::getPlansFilterFields($id, $common_plans, $advanced_plans));

    // TODO: Merge with advanced, add checked plans data (now, "active") and "advanced" if its an advanced plan
    $sources = \Mobbex\Repository::getSources();
} catch (\Exception $e) {
    $commonFields = $advancedFields = $sourceNames = [];
    $this->logger->log('error', "Template > getContent | {$e->getMessage()}");
}

include $this->getTemplateFile('Mobbex_Webpay::plans-filter.phtml');
include $this->getTemplateFile('Mobbex_Webpay::multivendor.phtml');
$this->helper->executeHook('mobbexCategorySettings', false, $id);
