<table class="mbbx-plans-cont">
    <tbody>
        <tr style="text-align: center;">
            <td><?= __('Planes comunes') ?></td>
            <td><?= __('Planes con reglas avanzadas') ?></td>
        </tr>
        <tr>
            <td class="mbbx-plans">
                <?php foreach ($commonFields as $field) : ?>
                    <div class="mbbx-plan">
                        <input type="checkbox" name="<?= $field['id'] ?>" <?= $field['value'] ? 'checked="checked"' : '' ?> id="<?= $field['id'] ?>" data-form-part="<?= $form ?>">
                        <label for="<?= $field['id'] ?>"><?= $field['label'] ?></label>
                    </div>
                <?php endforeach; ?>
            </td>
            <td class="mbbx-plans">
                <?php foreach ($advancedFields as $sourceRef => $fields) : ?>
                    <div class="mbbx-plan-source">
                        <img src="https://res.mobbex.com/images/sources/<?= $sourceRef ?>.png">
                        <p><?= $sourceNames[$sourceRef] ?></p>
                    </div>
                    <?php foreach ($fields as $field) : ?>
                        <div class="mbbx-plan-advanced">
                            <input type="checkbox" name="<?= $field['id'] ?>" <?= $field['value'] ? 'checked="checked"' : '' ?> id="<?= $field['id'] ?>" data-form-part="<?= $form ?>">
                            <label for="<?= $field['id'] ?>"><?= $field['label'] ?></label>
                        </div>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </td>
        </tr>
    </tbody>
</table>

<!-- Subscriptions -->
<?php if($isProduct): ?>
<div class="mbbx-subscription">
    <h3><?= __('Activar tipo suscripcion') ?></h3>
    <p><?= __('Activa si el producto es de tipo suscripción') ?></p>

    <label for="enable_sub" style="margin-right: 20px;"><?= __('Es suscripcion') ?></label>
    <select id="enable_sub" name="enable_sub" data-form-part="<?= $form ?>" onchange="document.querySelector('#subscription_uid').classList.toggle('hidden')">
        <option value="no" <?= $subscription['enable'] === 'no' ? 'selected' : '' ?>>No</option>
        <option value="yes" <?= $subscription['enable'] === 'yes' ? 'selected' : '' ?>>Yes</option>
    </select>
    <div class="<?= $subscription['enable'] === 'no' ? 'hidden' : '' ?>" id="subscription_uid" style="margin-top: 20px;">
        <label style="margin-right: 10px;" for="sub_uid"><?= __('UID de la Suscripción') ?></label>
        <input type="text" name="sub_uid" id="sub_uid" value="<?= $subscription['uid'] ?>" data-form-part="<?= $form ?>">
    </div>
</div>
<?php endif; ?>

<style>
    .hidden {
        display: none;
    }

    .mbbx-subscription{
        margin-top: 20px;
    }
    .mbbx-plans-cont {
        border: 1px gainsboro solid;
        width: 500px;
    }

    .mbbx-plans-cont tbody {
        vertical-align: top
    }

    .mbbx-plans-cont td {
        width: 50%;
        border: 1px gainsboro solid;
        padding: 15px;
    }

    .mbbx-plans-cont label {
        font-weight: 400 !important;
    }

    .mbbx-plan-advanced {
        padding-left: 20px;
    }

    .mbbx-plan-source * {
        display: inline;
    }

    .mbbx-plan-source img {
        width: 30px;
        border-radius: 100%;
    }
</style>