<table class="mbbx-plans-cont">
    <tbody>
        <tr style="text-align: center;">
            <td><?= __('Common Plans') ?></td>
            <td><?= __('Advanced Plans') ?></td>
        </tr>
        <tr>
            <td class="mbbx-plans">
                <?php foreach ($commonFields as $field) : ?>
                    <div class="mbbx-plan">

                            <div class="source-popover">
                                <h4>Medios Disponibles</h4>
                                <?php foreach ($sourceGroups[$field['label']] as $sourceRef) : ?>
                                    <div class="mbbx-plan-group">
                                        <img src="https://res.mobbex.com/images/sources/original/<?= $sourceRef; ?>.png">
                                        <small><?= isset($sourceNames[$sourceRef]) ? $sourceNames[$sourceRef] : $sourceRef ?></small>
                                    </div>
                                <?php endforeach; ?>
                            </div>

                        <div class="mbbx-plan-cont">
                            <input type="checkbox" name="<?= $field['id'] ?>" <?= $field['value'] ? 'checked="checked"' : '' ?> id="<?= $field['id'] ?>" data-form-part="<?= $form ?>">
                            <label for="<?= $field['id'] ?>"><?= $field['label'] ?></label>
                        </div>

                        <p class="description"><?= $field['description'] ?></p>

                    </div>
                <?php endforeach; ?>
            </td>

            <td class="mbbx-plans">
                <?php foreach ($advancedFields as $sourceRef => $fields) : ?>
                    <div class="mbbx-plan-source">
                        <img src="https://res.mobbex.com/images/sources/png/<?= $sourceRef ?>.png">
                        <p><?= $sourceNames[$sourceRef] ?></p>
                    </div>
                    <?php foreach ($fields as $field) : ?>
                        <div class="mbbx-plan-advanced">
                            <input type="checkbox" name="<?= $field['id'] ?>" <?= $field['value'] ? 'checked="checked"' : '' ?> id="<?= $field['id'] ?>" data-form-part="<?= $form ?>">
                            <label for="<?= $field['id'] ?>"><?= $field['label'] ?></label>
                            <p class="description"><?= $field['description'] ?></p>
                        </div>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </td>
        </tr>
    </tbody>
</table>

<style>
    .mbbx-plan {
        position: relative;
    }


    .mbbx-plans-cont {
        border: 1px gainsboro solid;
        width: 500px;
    }

    .mbbx-plans-cont tbody {
        vertical-align: top
    }

    .mbbx-plans-cont td {
        width: 50%;
        border: 1px gainsboro solid;
        padding: 15px;
    }

    .mbbx-plans-cont label {
        font-weight: 400 !important;
    }

    .mbbx-plans-cont .description {
        color: grey;
        font-size: 1.2rem;
    }

    .mbbx-plan-advanced {
        padding-left: 20px;
    }

    .mbbx-plan-source * {
        display: inline;
    }

    .mbbx-plan-source img {
        width: 30px;
        border-radius: 100%;
    }

    .mbbx-plan-cont {
        display: flex;
        align-items: center;
        padding: 0 10px;
    }

    .mbbx-plan-group {
        display: flex;
        justify-content: left;
        align-items: center;
        padding: 5px;
        background-color: #eaeffb;
    }

    .mbbx-plan-group img {
        width: 1.5em;
        margin: 0 5px;
    }

    .source-popover {
        opacity: 0;
        position: absolute;
        top: 2em;
        left: -15em;
        max-width: 15em;
        width: 100%;
        justify-content: center;
        flex-direction: column;
        border-radius: 5px;
        background-color: #eaeffb;
        padding: 1rem;
        z-index: 100;
        transition: opacity .8s linear(-0.03 52.95%, 1 72.28%);
    }

    .source-popover h3 {
        text-align: center;
    }

    .mbbx-plan:hover .source-popover {
        opacity: 1;
    }

    .mbbx-plan-group p {
        margin: 0;
    }
</style>