<h3><?= __('Configuración de planes') ?></h3>
<p><?= __('Los planes habilitados aparecerán en el checkout de este producto') ?></p>

<?php
extract($this->helper->getPlansFilterFields(isset($this->params['id']) ? $this->params['id'] : 0));
$form         = 'product_form';
$subscription = $this->helper->getProductSubscription(isset($this->params['id']) ? $this->params['id'] : 0);
$entity       = $this->helper->getProductEntity(isset($this->params['id']) ? $this->params['id'] : 0);
include $this->getTemplateFile('Mobbex_Webpay::plans-filter.phtml');
include $this->getTemplateFile('Mobbex_Webpay::multivendor.phtml');
include $this->getTemplateFile('Mobbex_Webpay::subscription.phtml');
