<h3><?= __('Configuración de planes') ?></h3>
<p><?= __('Los planes habilitados aparecerán en el checkout de este producto') ?></p>

<?php
extract($this->helper->getPlansFilterFields(isset($this->params['id']) ? $this->params['id'] : 0));
$form = 'product_form';
$entity = $this->helper->getEntity(isset($this->params['id']) ? $this->params['id'] : 0, 'product');
include $this->getTemplateFile('Mobbex_Webpay::prod&cat-config.phtml');
?>


<?php



