<h3><?= __('Configuración de planes') ?></h3>
<p><?= __('Los planes habilitados aparecerán en el checkout de este producto') ?></p>

<?php
$id           = isset($this->params['id']) ? $this->params['id'] : 0;
$form         = 'product_form';
$subscription = $this->helper->getProductSubscription($id);
$entity       = $this->helper->getProductEntity($id);
extract($this->helper->getPlansFilterFields($id));

include $this->getTemplateFile('Mobbex_Webpay::plans-filter.phtml');
include $this->getTemplateFile('Mobbex_Webpay::multivendor.phtml');
include $this->getTemplateFile('Mobbex_Webpay::subscription.phtml');
$this->helper->mobbex->executeHook('mobbexProductSettings', false, $id);