<!-- Subscriptions -->
<div class="mbbx-subscription">
    <h3><?= __('Subscription') ?></h3>
    <p><?= __('Turn this product a Mobbex Subscription') ?></p>

    <label for="enable_sub" style="margin-right: 20px;"><?= __('Is Subscription') ?></label>
    <select id="enable_sub" name="enable_sub" data-form-part="<?= $form ?>" onchange="document.querySelector('#subscription_uid').classList.toggle('hidden')">
        <option value="no" <?= $is_subscription === 'no' ? 'selected' : '' ?>>No</option>
        <option value="yes" <?= $is_subscription === 'yes' ? 'selected' : '' ?>>Yes</option>
    </select>
    <div class="<?= $is_subscription === 'no' || empty($is_subscription) ? 'hidden' : '' ?>" id="subscription_uid" style="margin-top: 20px;">
        <label style="margin-right: 10px;" for="sub_uid"><?= __('Subscription UID') ?></label>
        <input type="text" name="sub_uid" id="sub_uid" value="<?= $subscription_uid ?>" data-form-part="<?= $form ?>">
    </div>
</div>

<style>
    .hidden {
        display: none;
    }

    .mbbx-subscription {
        margin-top: 20px;
    }
</style>