name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.3, 7.4, 8.1]

    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
    - name: Install dependencies
      run: composer install --dev
    - name: Execute PHP php-compatibility
      uses: extdn/github-actions-m2/php-compatibility/8.1@master